name: Build, Test and Lint

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build, Test and Lint
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Lint
        run: make lint
